### ISSUE TITLE
Mod Throws Big Error after updating to Latest 1.21 Neoforge Builds

### ISSUE THREAD

**Issue by ModernGamingWorld** [baguchan/EnchantWithMob-Forge#10]
[22Jun2024 18:33:55.234] [Render thread/ERROR] [net.neoforged.fml.ModContainer/LOADING]: Caught exception during event net.neoforged.neoforge.client.event.EntityRenderersEvent$AddLayers@7cbe3c73 dispatch for modid enchantwithmob
java.lang.IllegalAccessError: class baguchan.enchantwithmob.client.ClientRegistrar tried to access private field net.minecraft.client.renderer.entity.EntityRenderDispatcher.renderers (baguchan.enchantwithmob.client.ClientRegistrar is in module enchantwithmob@1.21-18.1.0 of loader 'TRANSFORMER' @6ee5f485; net.minecraft.client.renderer.entity.EntityRenderDispatcher is in module minecraft@1.21 of loader 'TRANSFORMER' @6ee5f485)
	at TRANSFORMER/enchantwithmob@1.21-18.1.0/baguchan.enchantwithmob.client.ClientRegistrar.registerEntityRenders(ClientRegistrar.java:75) ~[enchantwithmob-1.21-18.1.0.jar%23374!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23106!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.1.jar%23106!/:?]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:188) ~[loader-4.0.6.jar%2399!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.lambda$postEvent$13(ModLoader.java:357) ~[loader-4.0.6.jar%2399!/:4.0]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:164) ~[loader-4.0.6.jar%2399!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.postEvent(ModLoader.java:357) ~[loader-4.0.6.jar%2399!/:4.0]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.entity.EntityRenderDispatcher.onResourceManagerReload(EntityRenderDispatcher.java:481) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.ResourceManagerReloadListener.lambda$reload$0(ResourceManagerReloadListener.java:15) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1158) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:810) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23327!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.6.jar%2399!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.6.jar%2399!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.6.jar%2399!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.6.jar%2399!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.3.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.3.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.3.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.3.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.3.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.3.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.3.jar%23101!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]

**Comment by baguchi** [comment]
fixed in EnchantWithMob 1.21-18.2.0!
