### ISSUE TITLE
Mod causes massive log spam crashing/freezing game eventually

### ISSUE THREAD

**Issue by PapaDimitri** [baguchan/EnchantWithMob-Forge#13]
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20236_(Entity.java:2791)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.EntitySizeEvent.onSetSize(EntitySizeEvent.java:32)
	at TRANSFORMER/enchantwithmob@1.20.1-11.12.1/baguchan.enchantwithmob.event.__EntitySizeEvent_onSetSize_Size.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3499)

**Comment by baguchi** [comment]
fixed!

**Comment by PapaDimitri** [comment]
Sry i forgot to add its forge not neoforge. Just to clarify sry

**Comment by baguchi** [comment]
It's okey 🤔

**Comment by PapaDimitri** [comment]
I thought maybe u didnt know and put a fix for neoforge that was for forge lmao
